➕ Add mysqlclient to requirements.txt because of the following Traceback
Traceback (most recent call last):
  File "/Users/takeshi/sandbox/streamlit-sandbox/.venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling
    result = func()
  File "/Users/takeshi/sandbox/streamlit-sandbox/.venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec
    exec(code, module.__dict__)  # noqa: S102
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/takeshi/sandbox/streamlit-sandbox/my_first_app.py", line 3, in <module>
    conn = st.connection("streamlit_db")
  File "/Users/takeshi/sandbox/streamlit-sandbox/.venv/lib/python3.13/site-packages/streamlit/runtime/connection_factory.py", line 435, in connection_factory
    raise ModuleNotFoundError(f"{e}. {extra_info}")
ModuleNotFoundError: No module named 'MySQLdb'. You need to install the 'mysqlclient' package to use this connection.